# Generated by Django 2.0.2 on 2018-02-06 16:03

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import User as auth_User

def create_roles(apps, se):
    if not settings.DEBUG:
        return
    User = apps.get_model('users', 'User')
    def create_role(role):
        u = User(
            username=role, is_staff=True,
            is_superuser=(role == 'admin')
        )
        auth_User.set_password(u, role)
        u.role = role
        u.save()
    for role in [
        'admin', 'editor', 'readonly', 'external'
    ]:
        create_role(role)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_role')
    ]

    operations = [
        migrations.RunPython(create_roles)
    ]
