# Generated by Django 2.0.2 on 2018-02-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('readonly', 'ReadOnly'), ('external', 'External')], default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
