# Generated by Django 2.0.2 on 2018-02-08 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISO_CODE', models.CharField(max_length=10)),
                ('name', models.CharField(db_column='country_name', max_length=200)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(db_column='requirement_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='requirement_name', max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('picture_image', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft'), ('DL', 'Deleted')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CountryRequirement',
            fields=[
                ('requirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Requirement')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Country')),
            ],
            bases=('app.requirement',),
        ),
        migrations.AddField(
            model_name='requirement',
            name='countries',
            field=models.ManyToManyField(through='app.CountryRequirement', to='app.Country'),
        ),
    ]
