# Generated by Django 2.0.2 on 2018-02-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180208_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
